### ISSUE TITLE
Type problem on fuzzbunch

### ISSUE THREAD

**Issue by Alamot** [mdiazcl/fuzzbunch-debian#1]
The strange typing/echoing problem is due to the pyreadline module. I commented out these lines in windows/fuzzbunch/iohandler.py and the problem is gone. :)

```
'''
try:
    try:
        import readline
    except ImportError:
        import pyreadline as readline
    HAVE_READLINE = True
except:
'''
HAVE_READLINE = False
```

**Comment by mdiazcl** [comment]
Thank you so much Alamot. I'll check it out!

**Comment by mdiazcl** [comment]
Fixed! Thank you Alamot.
I thanked your contribution in the readme.md!
